[phases.install]
cmds = "npm install"

[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "npx serve -s build"
limitOverride = {"containers":{"cpu":1,"memoryBytes":1000000000}}
sleepApplication = false
useLegacyStacker = false
multiRegionConfig = {"asia-southeast1-eqsg3a":{"numReplicas":1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10