[phases.install]
cmds = "npm install"

[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "npx serve -s build"
sleepApplication = false
useLegacyStacker = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10